//***** THIS PROTOTYPE PROJECT IS CURRENTLY NOT IN USE AND MAY NOT BE USED UNTIL IT HAS BEEN COMPLETED *****//
//***** THIS PROTOTYPE PROJECT IS CURRENTLY NOT IN USE AND MAY NOT BE USED UNTIL IT HAS BEEN COMPLETED *****//
//***** THIS PROTOTYPE PROJECT IS CURRENTLY NOT IN USE AND MAY NOT BE USED UNTIL IT HAS BEEN COMPLETED *****//
//***** THIS PROTOTYPE PROJECT IS CURRENTLY NOT IN USE AND MAY NOT BE USED UNTIL IT HAS BEEN COMPLETED *****//

public class Main 
{
	public static void main(String[] args)
	{
		String wikiUrl = args[0];
		//TODO
	}
}
